[work in progress] added tests for serialization.py
ablab/IsoQuant pull request #201
Opened 2024-06-13 11:59 UTC by cat-bug

2024-06-15 08:13 UTC, andrewprzh requested changes
all good! just add empty list tests please

2024-06-15 08:13 UTC, andrewprzh commented on tests/test_serialization.py
> +            ([True, False]),
could you add an empty list test?

2024-06-15 08:13 UTC, andrewprzh commented on tests/test_serialization.py
> +    @pytest.mark.parametrize(
could you add 1-2 empty lists here too?

2024-06-17 08:05 UTC, cat-bug commented on tests/test_serialization.py
> +    @pytest.mark.parametrize(
done

2024-06-17 08:12 UTC, cat-bug commented
coverage of `serialization.py` is increased from 39% to 97%

2024-06-19 08:53 UTC, andrewprzh approved these changes

2024-06-19 08:53 UTC, merged