added test for alignment_info.py
ablab/IsoQuant pull request #227
Opened 2024-08-22 14:28 UTC by cat-bug

also removed unused code, change the order of expected/actual in number of asserts

2024-08-24 13:18 UTC, andrewprzh requested changes
Looks good! Just a couple minor changes

2024-08-26 09:11 UTC, cat-bug commented on src/alignment_info.py
> +REGION_TO_CHECK_LEN = 12
done

2024-08-26 09:11 UTC, cat-bug commented on src/common.py
> +        return [cls.match, cls.seq_match, cls.seq_mismatch]
done

2024-08-26 09:11 UTC, cat-bug commented on src/common.py
> +        return [cls.match, cls.insertion, cls.deletion, cls.seq_match, cls.seq_mismatch]
done

2024-08-26 10:18 UTC, andrewprzh approved these changes

2024-08-26 10:18 UTC, merged